# Generated by Django 3.0.8 on 2020-08-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestTactic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('opponent', models.CharField(max_length=8)),
                ('formation_text', models.CharField(max_length=50)),
                ('formation_image', models.ImageField(upload_to='tactics/formations')),
                ('style_of_play_text', models.CharField(max_length=50)),
                ('style_of_play_image', models.ImageField(upload_to='tactics/style_of_play')),
                ('line_tactics_text', models.CharField(max_length=50)),
                ('line_tactics_image', models.ImageField(upload_to='tactics/line_tactics')),
                ('marking_offside_text', models.CharField(max_length=50)),
                ('marking_offside_image', models.ImageField(upload_to='tactics/marking_offside')),
                ('tackling_index_text', models.CharField(max_length=50)),
                ('tackling_index_image', models.ImageField(upload_to='tactics/tackling_index')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='banner.png', upload_to='sideshow_pics')),
                ('description', models.CharField(max_length=70)),
                ('link', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TacticSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTactic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('opponent', models.CharField(max_length=8)),
                ('formation_text', models.CharField(max_length=50)),
                ('formation_image', models.ImageField(upload_to='tactics/formations')),
                ('style_of_play_text', models.CharField(max_length=50)),
                ('style_of_play_image', models.ImageField(upload_to='tactics/style_of_play')),
                ('line_tactics_text', models.CharField(max_length=50)),
                ('line_tactics_image', models.ImageField(upload_to='tactics/line_tactics')),
                ('marking_offside_text', models.CharField(max_length=50)),
                ('marking_offside_image', models.ImageField(upload_to='tactics/marking_offside')),
                ('tackling_index_text', models.CharField(max_length=50)),
                ('tackling_index_image', models.ImageField(upload_to='tactics/tackling_index')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.TacticSection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
