# Generated by Django 3.0.8 on 2020-08-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20200804_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countertacticstronger',
            options={'verbose_name_plural': 'Counter tactics (stronger opponent)'},
        ),
        migrations.AlterModelOptions(
            name='countertacticweaker',
            options={'verbose_name_plural': 'Counter tactics (weaker opponent)'},
        ),
    ]
