# Generated by Django 3.0.8 on 2020-08-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20200804_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besttactic',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='countertacticstronger',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='countertacticweaker',
            name='opponent',
        ),
    ]
