# Generated by Django 3.0.8 on 2020-08-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20200805_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countertactic',
            name='section',
        ),
        migrations.DeleteModel(
            name='TacticSection',
        ),
    ]
