# Generated by Django 3.0.8 on 2020-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20200805_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnerTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='sideshow',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='sideshow',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
