# Generated by Django 3.0.8 on 2020-08-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20200807_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeginnerTips',
            new_name='BeginnerTip',
        ),
    ]
