# Generated by Django 3.0.8 on 2020-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20200808_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnertip',
            name='image',
            field=models.ImageField(default=1, upload_to='beginner_tips_images'),
            preserve_default=False,
        ),
    ]
