# Generated by Django 3.0.8 on 2020-08-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_player_playergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='title',
            new_name='name',
        ),
    ]
