# Generated by Django 3.0.8 on 2020-08-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20200808_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergroup',
            old_name='group',
            new_name='title',
        ),
    ]
