# Generated by Django 3.0.8 on 2020-08-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_auto_20200808_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergroup',
            name='keywords',
            field=models.CharField(default=models.CharField(max_length=20), max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
