# Generated by Django 3.0.8 on 2020-08-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_auto_20200808_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('keywords', models.CharField(default=models.CharField(max_length=20), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tip_image', models.ImageField(blank=True, null=True, upload_to='players/player_images')),
                ('content', models.CharField(max_length=1000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.TipGroup')),
            ],
        ),
    ]
