# Generated by Django 3.0.8 on 2020-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_auto_20200808_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='keywords',
            field=models.CharField(default=models.CharField(max_length=50), max_length=200),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tip',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipgroup',
            name='keywords',
            field=models.CharField(default=models.CharField(max_length=50), max_length=200),
        ),
        migrations.AlterField(
            model_name='tipgroup',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
