# Generated by Django 3.0.8 on 2020-08-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_auto_20200808_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnertip',
            name='content',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=1000),
        ),
        migrations.AlterField(
            model_name='besttactic',
            name='formation_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='besttactic',
            name='line_tactics_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='besttactic',
            name='marking_offside_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='besttactic',
            name='style_of_play_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='besttactic',
            name='tackling_index_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticstronger',
            name='formation_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticstronger',
            name='line_tactics_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticstronger',
            name='marking_offside_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticstronger',
            name='style_of_play_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticstronger',
            name='tackling_index_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticweaker',
            name='formation_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticweaker',
            name='line_tactics_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticweaker',
            name='marking_offside_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticweaker',
            name='style_of_play_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='countertacticweaker',
            name='tackling_index_text',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='content',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sideshow',
            name='content',
            field=models.CharField(help_text='Put //...// around a word if you wnat to make it bold', max_length=200),
        ),
    ]
