# Generated by Django 3.0.8 on 2020-08-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0019_auto_20200810_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countertacticstronger',
            options={'verbose_name_plural': 'Counter tactic (stronger opponent)'},
        ),
        migrations.AlterModelOptions(
            name='countertacticweaker',
            options={'verbose_name_plural': 'Counter tactic (weaker opponent)'},
        ),
        migrations.AlterField(
            model_name='beginnertip',
            name='content',
            field=models.CharField(help_text='BOLD: //x// to make x bold n/ LINK: --x@/link@-- to go page link with text x', max_length=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='content',
            field=models.CharField(help_text='BOLD: //x// to make x bold n/ LINK: --x@/link@-- to go page link with text x', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.CharField(help_text='BOLD: //x// to make x bold n/ LINK: --x@/link@-- to go page link with text x', max_length=1000),
        ),
    ]
